### PR TITLE
[OSS-3] Removal of JQuery dependency

### PR DESCRIPTION
**Pull request by monttda**
#4 JQuery dependency was removed and the corresponding changes were made
  leaving only JQlite dependency since this comes with Angular itself.

[Review on Reviewable](https://reviewable.io/reviews/monterail/angular-blocking-click/6)

### CODE REVIEW

**Comment by hodak** [comment]
*[blocking_click.js, line 56 \[r1\]](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6#-K57UdyLSuV8ZEKWyQaU:-K57UdyLSuV8ZEKWyQaV:354574253) ([raw file](https://github.com/monterail/angular-blocking-click/blob/a3f8fc2a5c6ae945096cf6c4ff80d9793bb560d2/blocking_click.js#L56)):*
I believe jqLite has a `css` method that can work as a setter, why not using it?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6)*

**Comment by monttda** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[blocking_click.js, line 56 \[r1\]](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6#-K57UdyLSuV8ZEKWyQaU:-K59xHzO48SSipMw6wn7:-1698121741) ([raw file](https://github.com/monterail/angular-blocking-click/blob/a3f8fc2a5c6ae945096cf6c4ff80d9793bb560d2/blocking_click.js#L56)):*
It does has a css setter : 

css() - Only retrieves inline-styles, does not call getComputedStyle(). As a setter, does not convert numbers to strings or append 'px', and also does not have automatic property prefixing.

But the reason of not using it is because originally my goal was to remove basically every jQuery (including jqLite) but then I asked on hipchat and after hearing that leaving jqLite was okey all the work was already done, so I decided to leave it as javascript instead of changing it to jqlite.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6)*

**Comment by jandudulski** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[blocking_click.js, line 44 \[r1\]](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6#-K5othPBY2afIuA3sDQT:-K5othPBY2afIuA3sDQU:-563291129) ([raw file](https://github.com/monterail/angular-blocking-click/blob/a3f8fc2a5c6ae945096cf6c4ff80d9793bb560d2/blocking_click.js#L44)):*
Please remove such comments from code. Such a thing should go to the [commit message](http://codetunes.com/2015/101-to-commit-message/).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6)*

**Comment by monttda** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[blocking_click.js, line 44 \[r1\]](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6#-K5othPBY2afIuA3sDQT:-K5oy0mniqyj9S86pc5n:-499146009) ([raw file](https://github.com/monterail/angular-blocking-click/blob/a3f8fc2a5c6ae945096cf6c4ff80d9793bb560d2/blocking_click.js#L44)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6)*

**Comment by jandudulski** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/monterail/angular-blocking-click/6)*

**Pull request merged**
